### PR TITLE
- introduce parameter setting methods + some tests

### PR DESCRIPTION
**Pull request by chripf**
Adressing #129 

I added some methods for setting parameters programatically. Left the "Parameters" property for compatibility reasons, but had to fix the getter there. It was obviously not used and threw errors when testing.

Added some unittests too.

### CODE REVIEW

**Comment by majorsilence** [comment]
Ignore the test failures for now.   I'll try to get some time tonight to finish the appveyor configuration.

**Comment by Gankov** [comment]
Pull request has conflicts. Please fix, and i will merge it.

**Comment by chripf** [comment]
I have some problems reproducing the issue here. The solution builds fine on Windows/VS 2015... - any hints?

**Comment by majorsilence** [comment]
@chripf pull the latest changes from majorsilence/My-FyiReporting into your fork to fix the conflicts.  Then push that back up to you github fork.  This pull request should then be merge-able. See the "command line instructions" under the section "This branch has conflicts that must be resolved".

**Comment by chripf** [comment]
@majorsilence followed your instructions  but had to fix a projectfile too - should be fine now.

**Pull request merged**
